# Generated by Django 3.2.13 on 2022-05-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender_jobs', '0004_alter_carrierjobs_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierjobs',
            name='contact_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='senderjobs',
            name='contact_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
